apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  labels:
    app: kibana
    type: backend
spec:
  selector:
    matchLabels:
      type: backend
  replicas: 3
  template:
    metadata:
      name: kibana-pod
      labels:
        app: kibana
        type: backend
    spec:
      containers:
        - name: kibana-container
          image: kibana
  