apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  labels:
    app: elasticsearch
    type: backend
spec:
  selector:
    matchLabels:
      type: backend
  replicas: 3
  template:
    metadata:
      name: elasticsearch-pod
      labels:
        app: elasticsearch
        type: backend
    spec:
      containers:
        - name: elasticsearch-container
          image: elasticsearch
  