apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 8001
  selector:
    app: elasticsearch
    type: backend